### ISSUE TITLE
contact i have problem :)

### ISSUE THREAD

**Issue by Mike9911x** [Torkosol/seed-phrase-generator#1]
Hi i can get your contact to telegram my friend :)

**Comment by Torkosol** [comment]
Hello, describe your problem here so that other people with a similar problem will find a solution

**Comment by Mike9911x** [comment]
Im wanna contact private for telegram if you can :)

**Comment by Mike9911x** [comment]
For mac dont work ;( why ?

**Comment by Mike9911x** [comment]
The program can be improved to also search for other cryptocurrencies sample usdt bnb ?
